import { expect, test } from "@playwright/test";
import path from "node:path";

test("imports, edits, autosaves and restores a PDF", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: /把 PDF 处理得/ })).toBeVisible();
  await page.locator('input[type="file"]').first().setInputFiles(path.resolve("fixtures/sample.pdf"));
  await expect(page).toHaveURL(/\/editor\//);
  await expect(page.getByText("第 1 页，共 1 页")).toBeVisible();
  const canvas = page.locator("section canvas").first();
  await expect.poll(() => canvas.evaluate((element) => (element as HTMLCanvasElement).width)).toBeGreaterThan(300);
  const sourceText = page.locator(".pdf-text-layer span").filter({ hasText: "Paperkit browser test" }).first();
  await expect(sourceText).toHaveText("Paperkit browser test");
  const selectSourceText = () => sourceText.evaluate((element) => {
    const range = document.createRange();
    range.selectNodeContents(element);
    const selection = window.getSelection()!;
    selection.removeAllRanges();
    selection.addRange(range);
    element.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
  });
  await selectSourceText();
  await expect(page.getByRole("toolbar", { name: "高亮颜色" })).toBeVisible();
  await page.getByRole("button", { name: "自定义高亮颜色" }).click();
  const customHighlight = page.getByRole("dialog", { name: "自定义高亮颜色面板" });
  await customHighlight.getByLabel("Hex 色值").fill("#8B5CF6");
  await customHighlight.getByRole("button", { name: "应用此颜色" }).click();
  await expect(page.locator('[data-editor-object-type="highlight"]')).toHaveCount(1);
  await page.getByRole("button", { name: "撤销" }).click();
  await expect(page.locator('[data-editor-object-type="highlight"]')).toHaveCount(0);
  await page.getByRole("button", { name: "高亮" }).click();
  const canvasBox = await canvas.boundingBox();
  expect(canvasBox).not.toBeNull();
  await page.mouse.click(canvasBox!.x + canvasBox!.width / 2, canvasBox!.y + canvasBox!.height / 2);
  await expect(page.locator('[data-editor-object-type="highlight"]')).toHaveCount(0);
  await selectSourceText();
  await expect(page.getByRole("toolbar", { name: "高亮颜色" })).toBeVisible();
  await expect(page.locator('[data-editor-object-type="highlight"]')).toHaveCount(0);
  await page.getByRole("button", { name: "绿色高亮" }).click();
  await expect(page.locator('[data-editor-object-type="highlight"]')).toHaveCount(1);
  await expect(page.getByRole("button", { name: "高亮" })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "矩形" }).click();
  await page.mouse.move(canvasBox!.x + 60, canvasBox!.y + 80);
  await page.mouse.down();
  await page.mouse.move(canvasBox!.x + 210, canvasBox!.y + 160);
  await page.mouse.up();
  const rectangle = page.locator('[data-editor-object-type="rect"]');
  await expect(rectangle).toHaveCount(1);
  await expect(rectangle).toHaveCSS("width", /1[4-6]\dpx/);
  await page.getByRole("button", { name: "线条" }).click();
  await page.mouse.move(canvasBox!.x + 280, canvasBox!.y + 200);
  await page.mouse.down();
  await page.mouse.move(canvasBox!.x + 130, canvasBox!.y + 110);
  await page.mouse.up();
  await expect(page.locator('[data-editor-object-type="line"]')).toHaveCount(1);
  await page.getByRole("button", { name: "画笔" }).click();
  await page.mouse.move(canvasBox!.x + 90, canvasBox!.y + 250);
  await page.mouse.down();
  await page.mouse.move(canvasBox!.x + 130, canvasBox!.y + 220);
  await page.mouse.move(canvasBox!.x + 175, canvasBox!.y + 265);
  await page.mouse.up();
  await expect(page.locator('[data-editor-object-type="pen"]')).toHaveCount(1);
  const pinchPrevented = await canvas.evaluate((element) => !element.dispatchEvent(new WheelEvent("wheel", { bubbles: true, cancelable: true, ctrlKey: true, deltaY: -80, clientX: 500, clientY: 400 })));
  expect(pinchPrevented).toBe(true);
  await expect(page.getByText("122%", { exact: true })).toBeVisible();
  const scrollPrevented = await canvas.evaluate((element) => !element.dispatchEvent(new WheelEvent("wheel", { bubbles: true, cancelable: true, deltaY: 80 })));
  expect(scrollPrevented).toBe(false);
  await expect(page.getByText("122%", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "文字" }).click();
  const box = await canvas.boundingBox();
  expect(box).not.toBeNull();
  await page.mouse.click(box!.x + box!.width / 2, box!.y + box!.height / 2);
  await expect(page.getByText("双击输入文字", { exact: true })).toBeVisible();
  await expect(page.getByText("已保存")).toBeVisible({ timeout: 5000 });
  await page.reload();
  await expect(page.getByText("双击输入文字", { exact: true })).toBeVisible();
  await expect(page.locator('[data-editor-object-type="pen"]')).toHaveCount(1);
});

test("renders the first page before loading every thumbnail in a long PDF", async ({ page }) => {
  await page.goto("/");
  const card = page.getByRole("heading", { name: "编辑 PDF" }).locator("..");
  await card.locator('input[type="file"]').setInputFiles(path.resolve("fixtures/sample-30-pages.pdf"));
  await expect(page).toHaveURL(/\/editor\//);
  await expect(page.getByText("第 1 页，共 30 页")).toBeVisible();
  const mainCanvas = page.getByLabel("PDF 文档区域，可使用触控板双指缩放").locator("canvas").first();
  await expect.poll(() => mainCanvas.evaluate((element) => (element as HTMLCanvasElement).width), { timeout: 5000 }).toBeGreaterThan(300);
  expect(await page.locator("aside").first().locator("canvas").count()).toBeLessThan(30);
});

test("merges several PDFs and accepts another file", async ({ page }) => {
  await page.goto("/");
  const card = page.getByRole("heading", { name: "合并 PDF" }).locator("..");
  await card.locator('input[type="file"]').setInputFiles([path.resolve("fixtures/sample.pdf"), path.resolve("fixtures/sample-3-pages.pdf")]);
  await expect(page).toHaveURL(/mode=merge/);
  await expect(page.getByText("已加入 2 个文件，共 4 页")).toBeVisible();
  await expect(page.getByText("第 1 页，共 4 页")).toBeVisible();
  await page.locator('aside input[type="file"]').setInputFiles(path.resolve("fixtures/sample.pdf"));
  await expect(page.getByText("已加入 1 个 PDF、1 页")).toBeVisible();
  await expect(page.getByText("第 5 页，共 5 页")).toBeVisible();
});

test("selects and exports split pages", async ({ page }) => {
  await page.goto("/");
  const card = page.getByRole("heading", { name: "拆分 PDF" }).locator("..");
  await card.locator('input[type="file"]').setInputFiles(path.resolve("fixtures/sample-3-pages.pdf"));
  await expect(page).toHaveURL(/mode=split/);
  await expect(page.getByText("已选择 3/3", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "偶数页" }).click();
  await expect(page.getByText("已选择 1/3", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "奇数页" }).click();
  await expect(page.getByText("已选择 2/3", { exact: true })).toBeVisible();
  const pdfDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "导出所选 PDF" }).click();
  await pdfDownload;
  const zipDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "逐页 ZIP" }).click();
  await zipDownload;
});

test("exports selected PDF pages from the editor", async ({ page }) => {
  await page.goto("/");
  const card = page.getByRole("heading", { name: "编辑 PDF" }).locator("..");
  await card.locator('input[type="file"]').setInputFiles(path.resolve("fixtures/sample-3-pages.pdf"));
  await expect(page.getByText("第 1 页，共 3 页")).toBeVisible();
  await page.getByRole("button", { name: "选择导出 PDF 页面" }).click();
  const dialog = page.getByRole("dialog", { name: "选择要导出的页面" });
  await dialog.getByRole("radio", { name: "自定义" }).check();
  await dialog.getByLabel("页码范围").fill("2-3");
  const download = page.waitForEvent("download");
  await dialog.getByRole("button", { name: "导出 2 页PDF" }).click();
  await download;
});
