import { PDFDocument, rgb, degrees, StandardFonts, type PDFPage } from "pdf-lib";
import type { DraftPage, EditorDraft, EditorObject } from "./editor-types";
import type { LocalAsset } from "./local-db";
export async function pdfPages(assets:LocalAsset[]):Promise<DraftPage[]>{const pages:DraftPage[]=[];for(const asset of assets){const doc=await PDFDocument.load(asset.data,{ignoreEncryption:false});for(let i=0;i<doc.getPageCount();i++){const p=doc.getPage(i);pages.push({id:crypto.randomUUID(),sourceAssetId:asset.id,sourcePageIndex:i,rotation:0,width:p.getWidth(),height:p.getHeight()});}}return pages;}
export async function imagesToPdf(files:File[],landscape=false){const doc=await PDFDocument.create();const [pw,ph]=landscape?[841.89,595.28]:[595.28,841.89];for(const f of files){const bytes=await f.arrayBuffer();const image=f.type==="image/png"?await doc.embedPng(bytes):await doc.embedJpg(bytes);const page=doc.addPage([pw,ph]);const scale=Math.min((pw-40)/image.width,(ph-40)/image.height);page.drawImage(image,{x:(pw-image.width*scale)/2,y:(ph-image.height*scale)/2,width:image.width*scale,height:image.height*scale});}return doc.save();}
const hex=(value:string)=>{const v=value.replace("#","");return rgb(parseInt(v.slice(0,2),16)/255,parseInt(v.slice(2,4),16)/255,parseInt(v.slice(4,6),16)/255)};
async function textPng(text:string,fontSize:number,color:string){const ratio=2,pad=6;const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d")!;ctx.font=`${fontSize*ratio}px "PingFang SC","Microsoft YaHei",sans-serif`;canvas.width=Math.ceil(ctx.measureText(text||" ").width+pad*ratio);canvas.height=Math.ceil(fontSize*1.45*ratio);ctx.scale(ratio,ratio);ctx.font=`${fontSize}px "PingFang SC","Microsoft YaHei",sans-serif`;ctx.fillStyle=color;ctx.textBaseline="top";ctx.fillText(text,0,0);return new Uint8Array(await (await fetch(canvas.toDataURL("image/png"))).arrayBuffer());}
async function drawObject(doc:PDFDocument,page:PDFPage,o:EditorObject){const c=hex(o.color);if(o.type==="text"){if(/^[\x00-\x7F]*$/.test(o.text||"")){const font=await doc.embedFont(StandardFonts.Helvetica);page.drawText(o.text||"",{x:o.x,y:o.y,size:o.fontSize||16,color:c,font,opacity:o.opacity});}else{const png=await doc.embedPng(await textPng(o.text||"",o.fontSize||16,o.color));page.drawImage(png,{x:o.x,y:o.y,width:o.width,height:o.height,opacity:o.opacity});}}else if((o.type==="image"||o.type==="signature")&&o.dataUrl){const bytes=await (await fetch(o.dataUrl)).arrayBuffer();const image=o.dataUrl.startsWith("data:image/jpeg")?await doc.embedJpg(bytes):await doc.embedPng(bytes);page.drawImage(image,{x:o.x,y:o.y,width:o.width,height:o.height,opacity:o.opacity});}else if(o.type==="line")page.drawLine({start:{x:o.x,y:o.y},end:{x:o.x+o.width,y:o.y+o.height},thickness:2,color:c,opacity:o.opacity});else page.drawRectangle({x:o.x,y:o.y,width:o.width,height:o.height,borderColor:c,borderWidth:o.type==="rect"?2:0,color:o.type==="highlight"?c:undefined,opacity:o.opacity});}
export async function exportPdf(assets:LocalAsset[],draft:EditorDraft,pageIds?:string[]){const output=await PDFDocument.create();const sources=new Map<string,PDFDocument>();for(const a of assets)sources.set(a.id,await PDFDocument.load(a.data));for(const p of draft.pages.filter(p=>!pageIds||pageIds.includes(p.id))){const source=sources.get(p.sourceAssetId);if(!source)continue;const [copy]=await output.copyPages(source,[p.sourcePageIndex]);output.addPage(copy);copy.setRotation(degrees((copy.getRotation().angle+p.rotation)%360));for(const o of draft.objects.filter(o=>o.pageId===p.id))await drawObject(output,copy,o);}return output.save();}
export function downloadBytes(bytes:Uint8Array,name:string,type="application/pdf"){const blob=new Blob([bytes as BlobPart],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function fileDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(r.error);r.readAsDataURL(file);});}
