"use client";
import { useEffect,useState } from "react";import Link from "next/link";import { FileText,Search,Trash2 } from "lucide-react";import { SiteHeader } from "@/components/site-header";import { deleteDocument,listDocuments,type LocalDocument } from "@/lib/local-db";import { ImportZone } from "@/components/import-zone";
export default function Documents(){
 const [docs,setDocs]=useState<LocalDocument[]>([]),[q,setQ]=useState("");
 useEffect(()=>{void(async()=>{const local=await listDocuments();if(process.env.NEXT_PUBLIC_CLOUD_ENABLED!=="true"){setDocs(local);return}const response=await fetch("/api/documents").catch(()=>null);if(!response?.ok){setDocs(local);return}const remote=await response.json(),known=new Set(local.map(d=>d.id));const cloud:LocalDocument[]=remote.filter((d:{id:string})=>!known.has(d.id)).map((d:{id:string;name:string;version:number;draft:LocalDocument["draft"];updatedAt:string})=>({id:d.id,name:d.name,version:d.version,draft:d.draft,updatedAt:new Date(d.updatedAt).getTime(),assets:[]}));setDocs([...local,...cloud].sort((a,b)=>b.updatedAt-a.updatedAt))})()},[]);
 const shown=docs.filter(d=>d.name.toLowerCase().includes(q.toLowerCase()));
 async function remove(id:string){await deleteDocument(id);if(process.env.NEXT_PUBLIC_CLOUD_ENABLED==="true")await fetch(`/api/documents/${id}`,{method:"DELETE"}).catch(()=>null);setDocs(v=>v.filter(x=>x.id!==id))}
 return <main className="min-h-screen bg-[#fafbfc]"><div className="bg-white"><SiteHeader/></div><section className="mx-auto max-w-6xl px-6 py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-4xl font-semibold tracking-[-.04em]">我的文档</h1><p className="mt-2 text-[#667085]">本地草稿与登录账号中的云端文档</p></div><ImportZone compact/></div><label className="mt-10 flex h-11 max-w-sm items-center gap-3 rounded-xl border border-[#d8deea] bg-white px-4 text-[#667085]"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="搜索文档名称"/></label>{shown.length?<div className="mt-6 overflow-hidden rounded-2xl border border-[#e5e9f0] bg-white">{shown.map((d,i)=><div key={d.id} className={`flex items-center gap-4 px-5 py-4 ${i?"border-t border-[#eef0f3]":""}`}><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#eef2ff] text-[#315ee7]"><FileText size={21}/></span><Link href={`/editor/${d.id}`} className="min-w-0 flex-1"><p className="truncate font-medium hover:text-[#315ee7]">{d.name}</p><p className="mt-1 text-xs text-[#7b8497]">{d.draft.pages.length} 页 · {new Date(d.updatedAt).toLocaleString("zh-CN")}</p></Link><button aria-label="删除" onClick={()=>void remove(d.id)} className="rounded-lg p-2 text-[#7b8497] hover:bg-red-50 hover:text-red-600"><Trash2 size={18}/></button></div>)}</div>:<div className="mt-16 text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#eef2ff] text-[#315ee7]"><FileText size={32}/></span><h2 className="mt-5 text-xl font-semibold">这里还没有文档</h2><p className="mt-2 text-sm text-[#667085]">导入一份 PDF，第一份草稿会自动出现在这里。</p></div>}</section></main>
}
